# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('current_menu_item', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='current_menu_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='current_menu_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='has_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Side'),
        ),
        migrations.AddField(
            model_name='side',
            name='current_menu_item',
            field=models.BooleanField(default=True),
        ),
    ]
