# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20171116_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Side'),
        ),
    ]
