# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', 'small'), ('MD', 'medium'), ('LG', 'large')], default='MD', max_length=2)),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.drink')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.meal')),
            ],
        ),
        migrations.CreateModel(
            name='side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.order')),
                ('side', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.side')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=150)),
                ('customer_email_address', models.EmailField(max_length=100)),
                ('customer_phone_number', models.IntegerField()),
                ('price_pretax_total', models.IntegerField()),
                ('price_tax', models.IntegerField()),
                ('price_posttax_total', models.IntegerField()),
                ('creation_time_and_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
