# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 20:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20171116_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Side'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Drink'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='side',
            name='side',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Side'),
        ),
        migrations.AlterField(
            model_name='side',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='subtraction',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Side'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
