# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20171116_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Side'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Drink'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='side',
            name='side',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Side'),
        ),
        migrations.AlterField(
            model_name='side',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='subtraction',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Side'),
        ),
    ]
